/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_STUBCLIENT_H_
#define JSONRPC_CPP_STUB_STUBCLIENT_H_

#include <jsonrpccpp/client.h>

// 存根生成器，自动生成的，客户端存根类
class StubClient : public jsonrpc::Client
{
    public:
        StubClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}
        
        // 供客户端程序client_main.cpp调用的，远程方法sayHello，该方法的真正的代码实现，在服务端程序中
        std::string sayHello(const std::string& name) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;// 存放：传递给远程方法sayHello的参数
            p["name"] = name;
            // 客户端程序，向服务端程序发送Json-Rpc远程方法调用请求，开始调用，服务端程序提供的远程方法sayHello
            // 使用result，接收，服务端程序提供的远程方法sayHello的计算结果
            Json::Value result = this->CallMethod("sayHello",p);
            if (result.isString())
                return result.asString();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        
        // 供客户端程序client_main.cpp调用的，远程通知notifyServer，该通知的真正的代码实现，在服务端程序中
        void notifyServer() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;// 存放：传递给远程通知notifyServer的参数
            p = Json::nullValue;
            // 客户端程序，向服务端程序发送Json-Rpc远程通知调用请求，开始调用，服务端程序提供的远程通知notifyServer
            this->CallNotification("notifyServer",p);
        }
};

#endif //JSONRPC_CPP_STUB_STUBCLIENT_H_
